Improve CodeBuild (#191)
* first attempt to add gnu

* a push

* add mca

* remove ecbuild_bundle eckit from CMakeLists

* remove  line with eckit

* debug

* debug

* debug

* use more resources

* debug

* debug

* debug

* debug

* whereis?

* clean up

* add intel

* rerun failed tests

* bugfix

* remove finally

* add aws status badge

* rerun failed tests

* run failed test in a separate line

* move rerun to post-build phase

* add rerun failed test with VV

* only run fv3-jedi tests

* rerun failed tests only in fv3-jedi

* make only fv3-jedi

* use -VV instead of -V and source compilervars.sh in intel rerun-failed

* bugfix

* get branch name from codebuild env variables

* use CODEBUILD_SOURCE_VERSION to determine branch name

* debug

* debug

* checkout same branch in ufo-bundle

* debug

* debug

* checkout same branch all repos

* same branch name for all bundle repos on gnu and intel

* trying to solve intel problem with getting branch name

* debug

* print CODEBUILD_BUILD_SUCCEEDING

* debug

* debug

* if statement for rerun

* bugfix

* debug

* debug

* debug

* debug

* if statement for gnu and intel

* if -z does not work, use =

diff --git a/buildspec_gnu.yml b/buildspec_gnu.yml
--- a/buildspec_gnu.yml
+++ b/buildspec_gnu.yml
@@ -9,9 +9,16 @@ phases:
   install:
     commands:
       - echo Executing install phase
-      - echo $CODEBUILD_WEBHOOK_TRIGGER
-      - echo $CODEBUILD_WEBHOOK_BASE_REF
+      - echo $CODEBUILD_WEBHOOK_TRIGGER 
+      - echo $CODEBUILD_WEBHOOK_BASE_REF 
+      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
+      - echo $CODEBUILD_WEBHOOK_EVENT
+      - echo $CODEBUILD_BUILD_SUCCEEDING
 
+      - CODEBUILD_GIT_BRANCH="$(git branch -a --contains $CODEBUILD_SOURCE_VERSION | sed -n 2p | awk '{ printf $1 }')";
+        export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/}
+      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
+      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"
 
       - echo MPI setup for Docker
       - mkdir -p /var/run/sshd
@@ -47,29 +54,61 @@ phases:
   pre_build:
     commands:
       - echo Executing pre_build phase
-      - my_branch=$(echo $CODEBUILD_WEBHOOK_TRIGGER| cut -d"/" -f2-)
-      - echo $my_branch
       - git lfs install # creates .gitconfig
       - cp ~/.gitconfig /home/jcsdauser/
+ 
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-bundle fv3-bundle
+      - cd fv3-bundle
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fv3-bundle repo"
+      - cd $CODEBUILD_SRC_DIR
+
+      # FV3-JEDI and the linearized model
+      - git clone -b $CODEBUILD_GIT_BRANCH https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi fv3-bundle/fv3-jedi
+
+      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi-linearmodel fv3-bundle/fv3-jedi-lm
+      - cd fv3-bundle/fv3-jedi-lm
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fv3-jedi-lm repo"
+      - cd $CODEBUILD_SRC_DIR
+
 
       # External observation operators
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/crtm fv3-bundle/crtm
+      - cd fv3-bundle/crtm
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in crtm repo"
+      - cd $CODEBUILD_SRC_DIR
 
       # Core JEDI repositories
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/saber fv3-bundle/saber
+      - cd fv3-bundle/saber
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in saber repo"
+      - cd $CODEBUILD_SRC_DIR
+
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/oops fv3-bundle/oops
+      - cd fv3-bundle/oops
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in oops repo"
+      - cd $CODEBUILD_SRC_DIR
+
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/ioda fv3-bundle/ioda
+      - cd fv3-bundle/ioda
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in ioda repo"
+      - cd $CODEBUILD_SRC_DIR
+
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/ufo fv3-bundle/ufo
+      - cd fv3-bundle/ufo
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in ufo repo"
+      - cd $CODEBUILD_SRC_DIR
 
       # FV3 based model and/or FMS
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/FMS fv3-bundle/fms
-
-      # FV3-JEDI and the linearized model
-      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi-linearmodel fv3-bundle/fv3-jedi-lm
-      - git clone -b $my_branch https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi fv3-bundle/fv3-jedi
+      - cd fv3-bundle/fms
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fms repo"
+      - cd $CODEBUILD_SRC_DIR
 
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fckit fv3-bundle/fckit
+      - cd fv3-bundle/fckit
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fckit repo"
+      - cd $CODEBUILD_SRC_DIR
+
 
       - ls
       - pwd
@@ -83,6 +122,7 @@ phases:
   build:
     commands:
       - echo Executing build phase
+      - echo $CODEBUILD_BUILD_SUCCEEDING
       - su - jcsdauser -c "cd /build_container 
         && echo $CC
         && echo $CXX
@@ -94,5 +134,10 @@ phases:
   post_build:
     commands:
       - echo Executing post_build phase
-      - su - jcsdauser -c "cd /build_container/fv3-jedi
-        && ctest -VV --rerun-failed"
+      - echo $CODEBUILD_BUILD_SUCCEEDING
+      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ]; 
+        then echo "Build Failing"; 
+        su - jcsdauser -c "cd /build_container/fv3-jedi
+        && ctest -VV --rerun-failed"; 
+        else echo "CODEBUILD_BUILD_SUCCEEDING=$CODEBUILD_BUILD_SUCCEEDING";
+        fi
diff --git a/buildspec_intel.yml b/buildspec_intel.yml
--- a/buildspec_intel.yml
+++ b/buildspec_intel.yml
@@ -11,6 +11,8 @@ phases:
       - echo Executing install phase
       - echo $CODEBUILD_WEBHOOK_TRIGGER
       - echo $CODEBUILD_WEBHOOK_BASE_REF
+      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
+      - echo $CODEBUILD_WEBHOOK_EVENT
 
 
       - echo MPI setup for Docker
@@ -60,29 +62,65 @@ phases:
   pre_build:
     commands:
       - echo Executing pre_build phase
-      - my_branch=$(echo $CODEBUILD_WEBHOOK_TRIGGER| cut -d"/" -f2-)
-      - echo $my_branch
       - git lfs install # creates .gitconfig
       - cp ~/.gitconfig /home/jcsdauser/
+
+      - CODEBUILD_GIT_BRANCH="$(git branch -a --contains $CODEBUILD_SOURCE_VERSION | sed -n 2p | awk '{ printf $1 }')";
+        export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/}
+      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
+      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"
+
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-bundle fv3-bundle
+      - cd fv3-bundle
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fv3-bundle repo"
+      - cd $CODEBUILD_SRC_DIR
+
+      # FV3-JEDI and the linearized model
+      - git clone -b $CODEBUILD_GIT_BRANCH https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi fv3-bundle/fv3-jedi
+
+      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi-linearmodel fv3-bundle/fv3-jedi-lm
+      - cd fv3-bundle/fv3-jedi-lm
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fv3-jedi-lm repo"
+      - cd $CODEBUILD_SRC_DIR
+
 
       # External observation operators
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/crtm fv3-bundle/crtm
+      - cd fv3-bundle/crtm
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in crtm repo"
+      - cd $CODEBUILD_SRC_DIR
 
       # Core JEDI repositories
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/saber fv3-bundle/saber
+      - cd fv3-bundle/saber
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in saber repo"
+      - cd $CODEBUILD_SRC_DIR
+
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/oops fv3-bundle/oops
+      - cd fv3-bundle/oops
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in oops repo"
+      - cd $CODEBUILD_SRC_DIR
+
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/ioda fv3-bundle/ioda
+      - cd fv3-bundle/ioda
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in ioda repo"
+      - cd $CODEBUILD_SRC_DIR
+
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/ufo fv3-bundle/ufo
+      - cd fv3-bundle/ufo
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in ufo repo"
+      - cd $CODEBUILD_SRC_DIR
 
       # FV3 based model and/or FMS
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/FMS fv3-bundle/fms
-
-      # FV3-JEDI and the linearized model
-      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi-linearmodel fv3-bundle/fv3-jedi-lm
-      - git clone -b $my_branch https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi fv3-bundle/fv3-jedi
+      - cd fv3-bundle/fms
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fms repo"
+      - cd $CODEBUILD_SRC_DIR
 
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fckit fv3-bundle/fckit
+      - cd fv3-bundle/fckit
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fckit repo"
+      - cd $CODEBUILD_SRC_DIR
 
       - ls
       - pwd
@@ -116,8 +154,10 @@ phases:
   post_build:
     commands:
       - echo Executing post_build phase
-
-      - su - jcsdauser -c "export COMPILERVARS_ARCHITECTURE=intel64
+      - echo $CODEBUILD_BUILD_SUCCEEDING
+      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ];
+        then echo "Build Failing";
+        su - jcsdauser -c "export COMPILERVARS_ARCHITECTURE=intel64
         && export COMPILERVARS_PLATFORM=linux
         && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
         && export FC=mpiifort
@@ -128,4 +168,6 @@ phases:
         && export LIBRARY_PATH=/usr/local/lib
         && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
         && cd /build_container/fv3-jedi/
-        && ctest -VV --rerun-failed"
+        && ctest -VV --rerun-failed";
+        else echo "CODEBUILD_BUILD_SUCCEEDING=$CODEBUILD_BUILD_SUCCEEDING";
+        fi
